version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_producto
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # Contraseña para el usuario root
      MYSQL_DATABASE: producto  # Nombre de la base de datos inicial
    ports:
      - "3307:3306"  # Mapea el puerto 3306 del contenedor al puerto 3307 en el host

  spring_app:
    build:
      context: .  # Contexto para construir la imagen
      dockerfile: Dockerfile  # Archivo Dockerfile a utilizar
    container_name: spring_producto
    environment:
      SPRING_APPLICATION_NAME: producto
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/producto  # URL para conectarse a MySQL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_SHOW_SQL:
    ports:
      - "8080:8080"
    depends_on:
      - mysql
